android.enableJetifier=true
android.nonTransitiveRClass=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx4096m -XX:+UseG1GC
org.gradle.daemon=false
ksp.incremental=false
# Versioning
VERSION_NAME=8.2.0
VERSION_CODE=820
APP_ID=com.goodwy.gallery
ksp.incremental=false
ksp.incremental.intermodule=false
